"""Published coaching reading titles by CEFR level and day (from vocab_storage)."""

from __future__ import annotations

from typing import Dict

COACHING_READING_TITLES_BY_LEVEL: Dict[str, Dict[int, str]] = {
    "A1": {
        1: "A Small Bag",
        2: "Dinner at Home",
        3: "My Breakfast",
        4: "A Busy Morning",
        5: "The Bus Stop",
        6: "A Rainy Day",
        7: "The Little Cat",
        8: "At the Small Shop",
        9: "In the Playground",
        10: "A Visit to the Doctor",
        11: "The English Lesson",
        12: "Grandma's House",
        13: "Lunch at School",
        14: "Anna's Busy Week",
        15: "A Walk in Town",
        16: "A Cold Morning",
        17: "The Dog and the Ball",
        18: "New Shoes",
        19: "Drawing Pictures",
        20: "Healthy Teeth",
        21: "The Lost Notebook",
        22: "A Family Photo",
        23: "Making a Sandwich",
        24: "A Weekend Morning",
        25: "The New Library",
        26: "Sunny Summer Days",
        27: "Birds in the Garden",
        28: "At the Market",
        29: "The Football Game",
        30: "A Healthy Day",
    },
    "A2": {
        1: "A Quiet Park",
        2: "My First Train Trip",
        3: "My First Job",
        4: "Learning the Guitar",
        5: "Cooking with Dad",
        6: "Walking to School",
        7: "A New Phone in the Family",
        8: "A Letter About Tet",
        9: "A Day at the Lake",
        10: "Saving for a Bike",
        11: "The Night Market",
        12: "The Wrong Bus",
        13: "Helping at the Shop",
        14: "A Free Saturday",
        15: "The Cooking Class",
        16: "Sleeping Better",
        17: "Video Calls with Grandma",
        18: "The School Festival",
        19: "The Small Garden",
        20: "Comparing Prices",
        21: "New Bike Lanes",
        22: "A Weekend Trip Plan",
        23: "The New Coworker",
        24: "The Photo Club",
        25: "Street Food Night",
        26: "A Visit to the Dentist",
        27: "Too Much Screen Time",
        28: "A Wedding in the Village",
        29: "Cleaning the Beach",
        30: "The Big Sale Decision",
    },
    "B1": {
        1: "Building a Study Habit",
        2: "Choosing a Part-Time Job",
        3: "Too Little Sleep",
        4: "A Homestay Summer",
        5: "Learning English with Apps",
        6: "Plastic in the River",
        7: "My Podcast Habit",
        8: "Teaching Kids on Weekends",
        9: "Joining a Running Club",
        10: "Eating Less Meat",
        11: "Dealing with Exam Stress",
        12: "My First Job Interview",
        13: "Exercise at Your Desk",
        14: "A Letter from Hoi An",
        15: "One Week Without Social Media",
        16: "Turning Down the City",
        17: "Is Reality TV Good or Bad?",
        18: "The Food Bank Next Door",
        19: "My First Five Kilometres",
        20: "What's on the School Plate?",
        21: "Why I Started a Third Language",
        22: "My First Month at Work",
        23: "The Phone Before Bed",
        24: "How I Travel on a Budget",
        25: "The New Rules of Online Shopping",
        26: "Growing Together: Community Gardens",
        27: "News or Noise?",
        28: "The Knock Next Door",
        29: "Our Company Football Team",
        30: "The True Cost of Fast Food",
    },
    "B2": {
        1: "City Trees and Urban Heat",
        2: "Food Waste in Supermarkets",
        3: "Three Sleep Myths, Tested by Science",
        4: "The Four-Day Week on Trial",
        5: "Why Clickbait Headlines Work",
        6: "The Sugar Tax Debate",
        7: "Should Homework Be Banned?",
        8: "The Speaker That Listens",
        9: "The Subscription You Forgot",
        10: "When the World Watches Your Film",
        11: "Building Streets for Bicycles",
        12: "Where Returned Clothes Really Go",
        13: "What Coffee Really Does to Your Focus",
        14: "Working from Home: Worth the Trade?",
        15: "How to Spot Misinformation Online",
        16: "Cleaning the Air in Crowded Cities",
        17: "Do University Rankings Tell the Truth?",
        18: "How Your Feed Decides What You See",
        19: "Why the Same Ticket Costs More at Night",
        20: "When Two Kitchens Meet",
        21: "Gardens on the Rooftops",
        22: "The Quiet Rise of the Repair Café",
        23: "Why a Sugar Pill Can Still Work",
        24: "Will the Machines Take Our Jobs?",
        25: "Are Podcasts Replacing the News?",
        26: "When the Doctor Prescribes a Walk",
        27: "Should Every Child Learn to Code?",
        28: "The Rise of the Digital Detox",
        29: "How Loyalty Programmes Really Work",
        30: "Global Brands and Local Identities",
    },
    "C1": {
        1: "Green Parks and Rising Rents",
        2: "Who Decides What Stays Online?",
        3: "The Minimum Wage Question",
        4: "Drawing Lines Around Gene Editing",
        5: "First in the Family",
        6: "The Clinic That Came to the Village",
        7: "When the Local Paper Closes",
        8: "Who Lives on the Floodplain?",
        9: "The Robots on the Warehouse Floor",
        10: "Bringing a Language Back to Life",
        11: "The Case for Car-Free Centres",
        12: "Taking Your Data With You",
        13: "When a Home Becomes an Asset",
        14: "Should an Algorithm Review the Science?",
        15: "The Quiet Advantage of Private Tutoring",
        16: "Paying People to Stay Well",
        17: "Who Should Pay for Public Broadcasting?",
        18: "When the Heat Becomes a Workplace Hazard",
        19: "Learning to Work Again",
        20: "Between Two Homes",
        21: "Whose Square Is It?",
        22: "Proving You Are Old Enough",
        23: "The Head Start Nobody Earns",
        24: "The Trials That Are Never Reported",
        25: "The Other Path",
        26: "The Ward That Cannot Keep Its Nurses",
        27: "The Mask and the Megaphone",
        28: "Who Pays for the Rising Water?",
        29: "The Human in the Loop",
        30: "What a Culture Chooses to Remember",
    },
    "C2": {
        1: "Convenience and Surveillance",
        2: "Does Language Shape Thought?",
        3: "The Illusion of Moral Progress",
        4: "The Attention Economy",
        5: "The Replication Crisis",
        6: "What Makes Art Valuable?",
        7: "Rhetoric After Truth",
        8: "The Arithmetic of Endless Growth",
        9: "The Gentle Hand on the Wheel",
        10: "What the Statues Ask of Us",
        11: "The Self, by the Numbers",
        12: "The Soft Words of Hard Power",
        13: "Counting the Cost of Doing Good",
        14: "The Gatekeepers of the Digital Square",
        15: "When the Public Wants Certainty",
        16: "The Machine in the Studio",
        17: "The Appearance of Agreement",
        18: "Less, Better: The Case Against Growth",
        19: "The Stories We Call Memories",
        20: "The Winners and the Records",
        21: "When the Algorithm Decides",
        22: "What Survives the Crossing",
        23: "Owing Something to the Unborn",
        24: "Homes as Assets",
        25: "The Map and the Territory",
        26: "Cleaning the Masters",
        27: "The Politics of Politeness",
        28: "Inventing the Wild",
        29: "We Are What We Repeat",
        30: "The Story Called Progress",
    },
}


def static_reading_titles(cefr_level: str) -> Dict[int, str]:
    return dict(COACHING_READING_TITLES_BY_LEVEL.get((cefr_level or "").upper(), {}))
