"""SQLAlchemy 2.0 declarative models for Postgres.

Conventions:
  * UUID primary keys generated by Postgres (`gen_random_uuid()`).
  * `created_at` / `updated_at` are timezone-aware UTC.
  * JSONB used for free-form metadata; first-class columns for anything
    we need to query/index.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from typing import Any, Dict, List, Optional

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# Identity
# ---------------------------------------------------------------------------


class User(Base):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    email: Mapped[str] = mapped_column(
        String(255), nullable=False, unique=True, index=True
    )
    password_hash: Mapped[Optional[str]] = mapped_column(String(255))
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    avatar_url: Mapped[Optional[str]] = mapped_column(Text)
    locale: Mapped[str] = mapped_column(String(8), nullable=False, server_default="en")
    timezone: Mapped[str] = mapped_column(
        String(64), nullable=False, server_default="UTC"
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="true"
    )
    email_verified: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )
    is_admin: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
    last_login_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))

    auth_providers: Mapped[List["AuthProvider"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    subscriptions: Mapped[List["Subscription"]] = relationship(back_populates="user")
    refresh_tokens: Mapped[List["RefreshToken"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class AuthProvider(Base):
    """One row per (user, provider, provider_uid). Allows linking multiple SSO."""

    __tablename__ = "auth_providers"
    __table_args__ = (
        UniqueConstraint("provider", "provider_uid", name="uq_auth_provider_uid"),
        Index("ix_auth_provider_user", "user_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    provider: Mapped[str] = mapped_column(String(32), nullable=False)
    provider_uid: Mapped[str] = mapped_column(String(255), nullable=False)
    payload: Mapped[Dict[str, Any]] = mapped_column(JSONB, server_default="{}")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    user: Mapped[User] = relationship(back_populates="auth_providers")


# ---------------------------------------------------------------------------
# Billing
# ---------------------------------------------------------------------------


class Plan(Base):
    __tablename__ = "plans"

    code: Mapped[str] = mapped_column(String(32), primary_key=True)
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    price_usd: Mapped[float] = mapped_column(
        Numeric(10, 2), nullable=False, server_default="0"
    )
    currency: Mapped[str] = mapped_column(
        String(3), nullable=False, server_default="USD"
    )

    monthly_assessments: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="5"
    )
    daily_ai_feedback: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="3"
    )
    daily_vocab_reviews: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="20"
    )
    can_create_personal_tasks: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )
    quarterly_discount: Mapped[float] = mapped_column(Numeric(5, 2), server_default="0")
    half_yearly_discount: Mapped[float] = mapped_column(
        Numeric(5, 2), server_default="0"
    )

    features: Mapped[Dict[str, Any]] = mapped_column(JSONB, server_default="{}")
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="true"
    )
    sort_order: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class Subscription(Base):
    __tablename__ = "subscriptions"
    __table_args__ = (
        Index("ix_subscriptions_user_status", "user_id", "status"),
        Index(
            "ix_subscriptions_active_period",
            "current_period_end",
            postgresql_where=(Column("status") == "active"),
        ),
        CheckConstraint(
            "billing_cycle in ('monthly','quarterly','half_yearly','annual')",
            name="ck_subscription_cycle",
        ),
        CheckConstraint(
            "status in ('active','past_due','cancelled','expired')",
            name="ck_subscription_status",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    plan_code: Mapped[str] = mapped_column(
        String(32), ForeignKey("plans.code"), nullable=False
    )
    billing_cycle: Mapped[str] = mapped_column(String(16), nullable=False)
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="active"
    )
    price_paid: Mapped[float] = mapped_column(
        Numeric(10, 2), nullable=False, server_default="0"
    )
    currency: Mapped[str] = mapped_column(
        String(3), nullable=False, server_default="USD"
    )
    current_period_start: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    current_period_end: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    auto_renewal: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )
    cancel_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    cancelled_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    payment_method: Mapped[Optional[str]] = mapped_column(String(32))
    external_subscription_id: Mapped[Optional[str]] = mapped_column(String(255))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    user: Mapped[User] = relationship(back_populates="subscriptions")


class Payment(Base):
    __tablename__ = "payments"
    __table_args__ = (
        UniqueConstraint(
            "provider", "provider_payment_id", name="uq_payment_provider_id"
        ),
        Index("ix_payments_user", "user_id"),
        CheckConstraint(
            "status in ('pending','succeeded','failed','refunded')",
            name="ck_payment_status",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    subscription_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("subscriptions.id", ondelete="SET NULL")
    )
    provider: Mapped[str] = mapped_column(String(32), nullable=False)
    provider_payment_id: Mapped[str] = mapped_column(String(255), nullable=False)
    amount_minor: Mapped[int] = mapped_column(Integer, nullable=False)
    currency: Mapped[str] = mapped_column(
        String(3), nullable=False, server_default="USD"
    )
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="pending"
    )
    plan_code: Mapped[Optional[str]] = mapped_column(String(32))
    months: Mapped[int] = mapped_column(Integer, nullable=False, server_default="1")
    metadata_: Mapped[Dict[str, Any]] = mapped_column(
        "metadata", JSONB, server_default="{}"
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


# ---------------------------------------------------------------------------
# Quota / usage
# ---------------------------------------------------------------------------


class UsageQuota(Base):
    """Counter rows.  `period_start` is the first day of the period
    (month for monthly limits, day for daily limits)."""

    __tablename__ = "usage_quota"
    __table_args__ = (
        UniqueConstraint(
            "user_id", "kind", "period_start", name="uq_usage_user_kind_period"
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    kind: Mapped[str] = mapped_column(String(32), nullable=False)
    period_start: Mapped[datetime] = mapped_column(Date, nullable=False)
    count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


# ---------------------------------------------------------------------------
# Refresh tokens
# ---------------------------------------------------------------------------


class RefreshToken(Base):
    __tablename__ = "refresh_tokens"
    __table_args__ = (Index("ix_refresh_user", "user_id"),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    token_hash: Mapped[str] = mapped_column(String(128), nullable=False, unique=True)
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    revoked_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    rotated_to: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))
    user_agent: Mapped[Optional[str]] = mapped_column(Text)
    ip_address: Mapped[Optional[str]] = mapped_column(String(64))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    user: Mapped[User] = relationship(back_populates="refresh_tokens")


# ---------------------------------------------------------------------------
# Public assessment lookup (auth boundary lives in PG)
# ---------------------------------------------------------------------------


class PublicAssessment(Base):
    __tablename__ = "public_assessments"

    public_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    submission_id: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    view_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))


# ---------------------------------------------------------------------------
# Vocabulary lexicon (CMS / content — user progress stays in Mongo)
# ---------------------------------------------------------------------------


class VocabLexeme(Base):
    """Canonical word entry keyed by (lemma, pos)."""

    __tablename__ = "vocab_lexemes"
    __table_args__ = (
        UniqueConstraint("lemma", "pos", name="uq_vocab_lexeme_lemma_pos"),
        Index("ix_vocab_lexeme_band", "ielts_band_min", "ielts_band_max"),
        Index("ix_vocab_lexeme_status", "status"),
        CheckConstraint(
            "status in ('draft','enriched','approved','deprecated')",
            name="ck_vocab_lexeme_status",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    lemma: Mapped[str] = mapped_column(String(128), nullable=False)
    display_word: Mapped[str] = mapped_column(String(128), nullable=False)
    pos: Mapped[str] = mapped_column(String(32), nullable=False)

    cefr_level: Mapped[Optional[str]] = mapped_column(String(8))
    ielts_band_min: Mapped[Optional[float]] = mapped_column(Numeric(3, 1))
    ielts_band_max: Mapped[Optional[float]] = mapped_column(Numeric(3, 1))
    gre_tier: Mapped[Optional[str]] = mapped_column(String(16))

    frequency_rank: Mapped[Optional[int]] = mapped_column(Integer)
    difficulty_score: Mapped[Optional[float]] = mapped_column(Numeric(6, 3))

    is_academic: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )
    is_ielts_relevant: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="true"
    )
    exam_types: Mapped[List[str]] = mapped_column(
        ARRAY(String(16)), nullable=False, server_default="{}"
    )
    sources: Mapped[List[Dict[str, Any]]] = mapped_column(JSONB, server_default="[]")
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="draft"
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    senses: Mapped[List["VocabSense"]] = relationship(
        back_populates="lexeme", cascade="all, delete-orphan"
    )
    word_forms: Mapped[List["VocabWordForm"]] = relationship(
        back_populates="lexeme", cascade="all, delete-orphan"
    )
    collocations: Mapped[List["VocabCollocation"]] = relationship(
        back_populates="lexeme", cascade="all, delete-orphan"
    )
    questions: Mapped[List["VocabQuestion"]] = relationship(
        back_populates="lexeme", cascade="all, delete-orphan"
    )
    pack_items: Mapped[List["VocabPackItem"]] = relationship(back_populates="lexeme")


class VocabSense(Base):
    __tablename__ = "vocab_senses"
    __table_args__ = (
        UniqueConstraint("lexeme_id", "sense_order", name="uq_vocab_sense_order"),
        Index("ix_vocab_sense_lexeme", "lexeme_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    lexeme_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vocab_lexemes.id", ondelete="CASCADE"),
        nullable=False,
    )
    sense_order: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="1"
    )
    definition_en: Mapped[str] = mapped_column(Text, nullable=False)
    phonetic: Mapped[Optional[str]] = mapped_column(String(64))
    audio_url: Mapped[Optional[str]] = mapped_column(Text)
    vi_gloss: Mapped[Optional[str]] = mapped_column(Text)
    register: Mapped[Optional[str]] = mapped_column(String(32))
    topic_tags: Mapped[List[str]] = mapped_column(
        ARRAY(String(64)), server_default="{}"
    )
    ielts_example: Mapped[Optional[str]] = mapped_column(Text)
    gre_example: Mapped[Optional[str]] = mapped_column(Text)
    common_mistake: Mapped[Optional[str]] = mapped_column(Text)
    vi_translate_prompt: Mapped[Optional[str]] = mapped_column(Text)
    topic_prompt: Mapped[Optional[str]] = mapped_column(Text)
    usage_note: Mapped[Optional[str]] = mapped_column(Text)
    synonyms: Mapped[List[str]] = mapped_column(JSONB, server_default="[]")
    tips: Mapped[List[str]] = mapped_column(JSONB, server_default="[]")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    lexeme: Mapped[VocabLexeme] = relationship(back_populates="senses")


class VocabWordForm(Base):
    __tablename__ = "vocab_word_forms"
    __table_args__ = (Index("ix_vocab_word_form_lexeme", "lexeme_id"),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    lexeme_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vocab_lexemes.id", ondelete="CASCADE"),
        nullable=False,
    )
    form: Mapped[str] = mapped_column(String(128), nullable=False)
    pos: Mapped[Optional[str]] = mapped_column(String(32))
    example: Mapped[Optional[str]] = mapped_column(Text)

    lexeme: Mapped["VocabLexeme"] = relationship(back_populates="word_forms")


class VocabCollocation(Base):
    __tablename__ = "vocab_collocations"
    __table_args__ = (Index("ix_vocab_collocation_lexeme", "lexeme_id"),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    lexeme_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vocab_lexemes.id", ondelete="CASCADE"),
        nullable=False,
    )
    phrase: Mapped[str] = mapped_column(String(255), nullable=False)
    pattern: Mapped[Optional[str]] = mapped_column(String(128))
    example: Mapped[Optional[str]] = mapped_column(Text)
    band_min: Mapped[Optional[float]] = mapped_column(Numeric(3, 1))
    is_core: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )

    lexeme: Mapped["VocabLexeme"] = relationship(back_populates="collocations")


class VocabPack(Base):
    __tablename__ = "vocab_packs"
    __table_args__ = (Index("ix_vocab_pack_sort", "sort_order"),)

    pack_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, server_default="")
    category: Mapped[str] = mapped_column(
        String(64), nullable=False, server_default="General"
    )
    task_type: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="Both"
    )
    exam_type: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="ielts"
    )
    pack_family: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="band"
    )
    skill_focus: Mapped[Optional[str]] = mapped_column(String(64))
    topic: Mapped[Optional[str]] = mapped_column(String(64))

    source_band_min: Mapped[float] = mapped_column(
        Numeric(3, 1), nullable=False, server_default="0"
    )
    source_band_max: Mapped[float] = mapped_column(
        Numeric(3, 1), nullable=False, server_default="9"
    )
    target_band_min: Mapped[float] = mapped_column(
        Numeric(3, 1), nullable=False, server_default="0"
    )
    target_band_max: Mapped[float] = mapped_column(
        Numeric(3, 1), nullable=False, server_default="9"
    )
    sort_order: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="true"
    )
    is_premium: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )
    content_status: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="draft"
    )
    target_word_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="12"
    )
    completed_word_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    items: Mapped[List["VocabPackItem"]] = relationship(
        back_populates="pack", cascade="all, delete-orphan"
    )


class VocabPackItem(Base):
    __tablename__ = "vocab_pack_items"
    __table_args__ = (
        UniqueConstraint("pack_id", "lexeme_id", name="uq_vocab_pack_item"),
        Index("ix_vocab_pack_item_order", "pack_id", "order_index"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    pack_id: Mapped[str] = mapped_column(
        String(64),
        ForeignKey("vocab_packs.pack_id", ondelete="CASCADE"),
        nullable=False,
    )
    lexeme_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vocab_lexemes.id", ondelete="CASCADE"),
        nullable=False,
    )
    sense_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("vocab_senses.id", ondelete="SET NULL")
    )
    order_index: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    is_core: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="true"
    )
    stat_labels: Mapped[List[str]] = mapped_column(
        ARRAY(String(32)), nullable=False, server_default="{}"
    )

    pack: Mapped[VocabPack] = relationship(back_populates="items")
    lexeme: Mapped[VocabLexeme] = relationship(back_populates="pack_items")


class VocabQuestion(Base):
    __tablename__ = "vocab_questions"
    __table_args__ = (
        Index("ix_vocab_question_lexeme", "lexeme_id", "task_type", "status"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    lexeme_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vocab_lexemes.id", ondelete="CASCADE"),
        nullable=False,
    )
    sense_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("vocab_senses.id", ondelete="SET NULL")
    )
    track_id: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="cefr:B1"
    )
    # Production DB column is task_type; Python attribute stays "type" for API/repos.
    type: Mapped[str] = mapped_column("task_type", String(64), nullable=False)
    skill: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="meaning"
    )
    level_code: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="B1"
    )
    mastery_slot: Mapped[Optional[int]] = mapped_column(Integer)
    interaction_kind: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="mcq"
    )
    prompt: Mapped[str] = mapped_column(Text, nullable=False)
    options: Mapped[List[Dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, server_default="[]"
    )
    correct_option_id: Mapped[str] = mapped_column(String(8), nullable=False)
    explanation: Mapped[Optional[str]] = mapped_column(Text)
    payload: Mapped[Dict[str, Any]] = mapped_column(JSONB, server_default="{}")
    difficulty: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="3", insert_default=3
    )
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="generated"
    )
    generator_meta: Mapped[Dict[str, Any]] = mapped_column(JSONB, server_default="{}")
    quality_score: Mapped[Optional[int]] = mapped_column(Integer)
    quality_tier: Mapped[Optional[str]] = mapped_column(String(16))
    quality_issues: Mapped[List[str]] = mapped_column(
        JSONB, nullable=False, server_default="[]"
    )
    content_revision: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="1"
    )
    sense_content_hash: Mapped[Optional[str]] = mapped_column(String(64))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    lexeme: Mapped[VocabLexeme] = relationship(back_populates="questions")


class VocabReviewQueue(Base):
    __tablename__ = "vocab_review_queue"
    __table_args__ = (Index("ix_vocab_review_priority", "priority", "resolved_at"),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    question_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vocab_questions.id", ondelete="CASCADE"),
        nullable=False,
    )
    priority: Mapped[int] = mapped_column(Integer, nullable=False, server_default="5")
    reviewer_notes: Mapped[Optional[str]] = mapped_column(Text)
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class VocabLegacyWordMap(Base):
    """Maps old Mongo pack-scoped word_id to global lexeme_id."""

    __tablename__ = "vocab_legacy_word_map"

    legacy_word_id: Mapped[str] = mapped_column(String(128), primary_key=True)
    lexeme_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vocab_lexemes.id", ondelete="CASCADE"),
        nullable=False,
    )
    pack_id: Mapped[Optional[str]] = mapped_column(String(64))


# ---------------------------------------------------------------------------
# Learning personalization (Postgres hybrid tracking)
# ---------------------------------------------------------------------------


class LearningEvent(Base):
    """Append-only learner action log for personalization.

    The MVP writes vocab events only, but source/content columns are generic so
    writing and grammar can feed the same pipeline later.
    """

    __tablename__ = "learning_events"
    __table_args__ = (
        UniqueConstraint("event_id", name="uq_learning_event_id"),
        Index("ix_learning_events_user_time", "user_id", "occurred_at"),
        Index("ix_learning_events_user_content", "user_id", "content_type", "word_id"),
        Index("ix_learning_events_pack_time", "pack_id", "occurred_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    event_id: Mapped[str] = mapped_column(String(128), nullable=False)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    event_type: Mapped[str] = mapped_column(String(64), nullable=False)
    source_content_type: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="vocabulary"
    )
    content_type: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="vocabulary"
    )
    word_id: Mapped[Optional[str]] = mapped_column(String(128))
    lexeme_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("vocab_lexemes.id", ondelete="SET NULL")
    )
    pack_id: Mapped[Optional[str]] = mapped_column(String(64))
    question_type: Mapped[Optional[str]] = mapped_column(String(64))
    step: Mapped[Optional[str]] = mapped_column(String(64))
    is_correct: Mapped[Optional[bool]] = mapped_column(Boolean)
    score: Mapped[Optional[float]] = mapped_column(Numeric(6, 3))
    time_taken: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    answer_meta: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    ai_eval_meta: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    weakness_tags: Mapped[List[str]] = mapped_column(
        JSONB, nullable=False, server_default="[]"
    )
    workout_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))
    workout_item_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))
    skill_id: Mapped[Optional[str]] = mapped_column(String(32))
    mastery_slot: Mapped[Optional[int]] = mapped_column(Integer)
    interaction_kind: Mapped[Optional[str]] = mapped_column(String(16))
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class VocabUserWordState(Base):
    __tablename__ = "vocab_user_word_state"
    __table_args__ = (
        UniqueConstraint("user_id", "word_id", name="uq_vocab_user_word_state"),
        Index("ix_vocab_word_state_user_due", "user_id", "due_at"),
        Index("ix_vocab_word_state_user_pack", "user_id", "pack_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    word_id: Mapped[str] = mapped_column(String(128), nullable=False)
    lexeme_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("vocab_lexemes.id", ondelete="SET NULL")
    )
    pack_id: Mapped[Optional[str]] = mapped_column(String(64))
    mastery_level: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="new"
    )
    mastery_step: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    mastery_point_pct: Mapped[float] = mapped_column(
        Numeric(8, 4), nullable=False, server_default="0"
    )
    due_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    failed_locked_until: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True)
    )
    marked_known: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )
    best_translate_pct: Mapped[float] = mapped_column(
        Numeric(8, 4), nullable=False, server_default="0"
    )
    best_topic_pct: Mapped[float] = mapped_column(
        Numeric(8, 4), nullable=False, server_default="0"
    )
    last_result: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    progress_data: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    weakness_tags: Mapped[List[str]] = mapped_column(
        JSONB, nullable=False, server_default="[]"
    )
    first_studied_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True)
    )
    last_studied_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class VocabUserPackState(Base):
    __tablename__ = "vocab_user_pack_state"
    __table_args__ = (
        UniqueConstraint("user_id", "pack_id", name="uq_vocab_user_pack_state"),
        Index("ix_vocab_pack_state_user_band", "user_id", "focus_band"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    pack_id: Mapped[str] = mapped_column(String(64), nullable=False)
    mastery_pct: Mapped[float] = mapped_column(
        Numeric(8, 4), nullable=False, server_default="0"
    )
    learned_words: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    mastered_words: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    focus_band: Mapped[Optional[float]] = mapped_column(Numeric(3, 1))
    active_band_meta: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    last_decay_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    last_studied_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class UserLearningDailyRollup(Base):
    __tablename__ = "user_learning_daily_rollups"
    __table_args__ = (
        UniqueConstraint("user_id", "day", name="uq_user_learning_daily_rollup"),
        Index("ix_user_learning_rollup_user_day", "user_id", "day"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    day: Mapped[date] = mapped_column(Date, nullable=False)
    focus_band: Mapped[Optional[float]] = mapped_column(Numeric(3, 1))
    action_counts: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    weak_dimensions: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    pack_counts: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    category_counts: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    correct_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    incorrect_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    total_time_taken: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class UserLearningWeakness(Base):
    __tablename__ = "user_learning_weaknesses"
    __table_args__ = (
        UniqueConstraint(
            "user_id", "dimension", "label", name="uq_user_learning_weakness"
        ),
        Index("ix_user_learning_weakness_user_severity", "user_id", "severity"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    dimension: Mapped[str] = mapped_column(String(64), nullable=False)
    label: Mapped[str] = mapped_column(String(128), nullable=False)
    severity: Mapped[float] = mapped_column(
        Numeric(6, 3), nullable=False, server_default="0"
    )
    evidence_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    recommended_action_type: Mapped[str] = mapped_column(
        String(64), nullable=False, server_default="repair_weakness"
    )
    pack_id: Mapped[Optional[str]] = mapped_column(String(64))
    stat_label: Mapped[Optional[str]] = mapped_column(String(64))
    band: Mapped[Optional[float]] = mapped_column(Numeric(3, 1))
    evidence: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    success_streak: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class VocabDailyMission(Base):
    __tablename__ = "vocab_daily_missions"
    __table_args__ = (
        UniqueConstraint(
            "user_id", "mission_date", "locale", name="uq_vocab_daily_mission"
        ),
        Index("ix_vocab_daily_mission_user_date", "user_id", "mission_date"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    mission_date: Mapped[date] = mapped_column(Date, nullable=False)
    locale: Mapped[str] = mapped_column(String(8), nullable=False, server_default="en")
    snapshot_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    output: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    model_provider: Mapped[Optional[str]] = mapped_column(String(32))
    model_name: Mapped[Optional[str]] = mapped_column(String(128))
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="generated"
    )
    refresh_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    error_meta: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class VocabCoachingWorkout(Base):
    __tablename__ = "vocab_coaching_workouts"
    __table_args__ = (
        UniqueConstraint(
            "user_id", "workout_date", "track_id", name="uq_vocab_coaching_workout_day"
        ),
        Index("ix_vocab_coaching_workout_user_date", "user_id", "workout_date"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    workout_date: Mapped[date] = mapped_column(Date, nullable=False)
    track_id: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="cefr:B1"
    )
    cefr_level: Mapped[str] = mapped_column(
        String(8), nullable=False, server_default="B1"
    )
    status: Mapped[str] = mapped_column(
        String(24), nullable=False, server_default="ready"
    )
    focus_skill: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="meaning"
    )
    intensity: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default="standard"
    )
    estimated_minutes: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="10"
    )
    coach_copy: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    progress: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    summary: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class VocabCoachingWorkoutItem(Base):
    __tablename__ = "vocab_coaching_workout_items"
    __table_args__ = (
        UniqueConstraint(
            "workout_id", "order_index", name="uq_vocab_coaching_workout_item_order"
        ),
        Index("ix_vocab_coaching_item_workout_order", "workout_id", "order_index"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    workout_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vocab_coaching_workouts.id", ondelete="CASCADE"),
        nullable=False,
    )
    phase: Mapped[str] = mapped_column(String(16), nullable=False)
    order_index: Mapped[int] = mapped_column(Integer, nullable=False)
    word_id: Mapped[str] = mapped_column(String(128), nullable=False)
    question_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vocab_questions.id", ondelete="CASCADE"),
        nullable=False,
    )
    mastery_slot: Mapped[int] = mapped_column(Integer, nullable=False)
    skill_id: Mapped[str] = mapped_column(String(32), nullable=False)
    interaction_kind: Mapped[str] = mapped_column(String(16), nullable=False)
    is_required: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="true"
    )
    status: Mapped[str] = mapped_column(
        String(24), nullable=False, server_default="pending"
    )
    attempt_id: Mapped[Optional[str]] = mapped_column(String(128))
    result: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    repair_parent_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vocab_coaching_workout_items.id", ondelete="SET NULL"),
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class VocabUserSkillState(Base):
    __tablename__ = "vocab_user_skill_state"
    __table_args__ = (
        UniqueConstraint(
            "user_id", "track_id", "skill_id", name="uq_vocab_user_skill_state"
        ),
        Index("ix_vocab_user_skill_state_user_due", "user_id", "due_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    track_id: Mapped[str] = mapped_column(String(32), nullable=False)
    skill_id: Mapped[str] = mapped_column(String(32), nullable=False)
    score: Mapped[float] = mapped_column(
        Numeric(6, 3), nullable=False, server_default="0"
    )
    evidence_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    correct_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    incorrect_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    success_streak: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    due_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    last_seen_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


# ---------------------------------------------------------------------------
# Writing (Postgres-only; formerly Mongo)
# ---------------------------------------------------------------------------


class WritingGroup(Base):
    __tablename__ = "writing_groups"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    icon: Mapped[Optional[str]] = mapped_column(String(64))
    sort_order: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    total_tasks: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="true"
    )


class WritingTask(Base):
    __tablename__ = "writing_tasks"
    __table_args__ = (
        Index("ix_writing_task_group", "group_id"),
        Index("ix_writing_task_personal", "created_by", "is_personal"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    group_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("writing_groups.id", ondelete="CASCADE"), nullable=False
    )
    group_name: Mapped[str] = mapped_column(String(255), nullable=False)
    task_type: Mapped[str] = mapped_column(String(32), nullable=False)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, server_default="")
    image_url: Mapped[Optional[str]] = mapped_column(Text)
    data_description: Mapped[Optional[str]] = mapped_column(Text)
    time_limit: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="1200"
    )
    difficulty: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="intermediate"
    )
    tags: Mapped[List[str]] = mapped_column(
        ARRAY(String(64)), nullable=False, server_default="{}"
    )
    access: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    tests_taken: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    average_score: Mapped[float] = mapped_column(
        Numeric(4, 2), nullable=False, server_default="0"
    )
    created_by: Mapped[Optional[str]] = mapped_column(String(128))
    is_personal: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class WritingSubmission(Base):
    __tablename__ = "writing_submissions"
    __table_args__ = (
        Index("ix_writing_sub_user_created", "user_id", "created_at"),
        Index("ix_writing_sub_status_finished", "status", "finished_at"),
        Index("ix_writing_sub_task", "task_id"),
    )

    submission_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    task_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("writing_tasks.id", ondelete="CASCADE"), nullable=False
    )
    answer: Mapped[str] = mapped_column(Text, nullable=False)
    word_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="queued"
    )
    task_snapshot: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    assessment: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSONB)
    error_message: Mapped[Optional[str]] = mapped_column(Text)
    prompt_version: Mapped[Optional[str]] = mapped_column(String(64))
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class GrammarStructure(Base):
    __tablename__ = "grammar_structures"
    __table_args__ = (Index("ix_grammar_structure_category", "category"),)

    structure_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    structure_pattern: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, server_default="")
    category: Mapped[str] = mapped_column(String(64), nullable=False)
    task_type: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="Both"
    )
    band_score: Mapped[float] = mapped_column(
        Numeric(3, 1), nullable=False, server_default="6.0"
    )
    difficulty_level: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="intermediate"
    )
    examples: Mapped[List[Dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, server_default="[]"
    )
    common_errors: Mapped[List[Dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, server_default="[]"
    )
    tags: Mapped[List[str]] = mapped_column(JSONB, nullable=False, server_default="[]")
    total_attempts: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    success_rate: Mapped[float] = mapped_column(
        Numeric(5, 4), nullable=False, server_default="0"
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="true"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class GrammarLearningProgress(Base):
    __tablename__ = "grammar_learning_progress"
    __table_args__ = (
        UniqueConstraint(
            "user_id", "structure_id", name="uq_grammar_learning_progress"
        ),
        Index("ix_grammar_progress_user", "user_id", "last_studied_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    structure_id: Mapped[str] = mapped_column(String(64), nullable=False)
    mastery_level: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="new"
    )
    progress_data: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    last_studied_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class UserLearningStats(Base):
    __tablename__ = "user_learning_stats"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        primary_key=True,
    )
    grammar_total_learned: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    grammar_mastered: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    grammar_accuracy: Mapped[float] = mapped_column(
        Numeric(5, 4), nullable=False, server_default="0"
    )
    grammar_current_streak: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    grammar_best_streak: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    vocab_total_learned: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    vocab_mastered: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    vocab_accuracy: Mapped[float] = mapped_column(
        Numeric(5, 4), nullable=False, server_default="0"
    )
    vocab_current_streak: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    vocab_best_streak: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    total_study_time: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    today_study_time: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    estimated_grammar_band: Mapped[float] = mapped_column(
        Numeric(3, 1), nullable=False, server_default="5.0"
    )
    estimated_vocab_band: Mapped[float] = mapped_column(
        Numeric(3, 1), nullable=False, server_default="5.0"
    )
    vocab_profile: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    daily_activity: Mapped[Dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default="{}"
    )
    last_activity: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class VocabAttempt(Base):
    __tablename__ = "vocab_attempts"
    __table_args__ = (Index("ix_vocab_attempt_user_created", "user_id", "created_at"),)

    attempt_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    word_id: Mapped[str] = mapped_column(String(128), nullable=False)
    pack_id: Mapped[Optional[str]] = mapped_column(String(64))
    attempt_type: Mapped[str] = mapped_column(String(64), nullable=False)
    is_correct: Mapped[Optional[bool]] = mapped_column(Boolean)
    answer: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSONB)
    ai_feedback: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
